name: strings
version: 0.1.0
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: The 'strings' is a helper for the string transformation which can be useful in the code generators (such as 'camelize', 'escape', 'underscore' etc).
homepage: https://github.com/mezoni/strings.git
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  lists: ^0.0.23
  unicode: ^0.1.0
dev_dependencies:
  test: ^1.3.0
