name: strings
version: 0.1.3
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: The 'strings' is a helper for the string transformation which can be useful in the code generators (such as 'camelize', 'escape', 'underscore' etc).
homepage: https://github.com/mezoni/strings.git
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  characters: ^1.0.0
  unicode: ^0.2.2
dev_dependencies:
  test: ^1.9.1
